import os
import gradio as gr
import functools
from openai import OpenAI
from dotenv import load_dotenv

try:
    from langchain_community.utilities import SerpAPIWrapper
except ImportError:
    raise ImportError("Please ensure langchain-community is installed via requirements.txt")

# Load environment variables from .env file if available
load_dotenv()

# Set up API keys
NVIDIA_API_KEY = os.environ.get('NVIDIA_API_KEY')
SERPAPI_API_KEY = os.environ.get('SERPAPI_API_KEY')

if not NVIDIA_API_KEY:
    print("WARNING: NVIDIA_API_KEY not found in environment. The LLM will not function correctly.")

# Ensure SERPAPI_API_KEY is available in the environment for langchain to pick up
if SERPAPI_API_KEY:
    os.environ["SERPAPI_API_KEY"] = SERPAPI_API_KEY
else:
    print("WARNING: SERPAPI_API_KEY not found in environment. Search fallbacks will activate.")

# Initialize the OpenAI client pointing to Nvidia's inference endpoints
client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=NVIDIA_API_KEY
)

# Initialize Search Wrapper
try:
    search = SerpAPIWrapper()
except Exception as e:
    search = None
    print(f"Failed to initialize SerpAPIWrapper: {e}")

@functools.lru_cache(maxsize=128)
def get_realtime_search_results(query: str) -> str:
    """
    Performs a real-time search using SerpAPIWrapper, parses the results,
    and returns a formatted string for use in a RAG system.
    """
    if not search:
        return "Real-time search results could not be retrieved due to initialization error."
        
    print(f"Searching for: {query}")
    try:
        results = search.run(query)
        formatted_output = []
        if isinstance(results, list) and results:
            for i, res in enumerate(results):
                title = res.get('title', 'N/A')
                link = res.get('link', 'N/A')
                source = res.get('source', 'N/A')
                date = res.get('date', 'N/A')
                formatted_output.append(f"Result {i+1}:\nTitle: {title}\nLink: {link}\nSource: {source}\nDate: {date}\n")
        elif isinstance(results, str) and results:
            formatted_output.append(results)
        else:
            formatted_output.append("No search results found.")
        return "\n".join(formatted_output)
    except Exception as e:
        print(f"Error during SerpAPI search: {e}")
        return "Real-time search results could not be retrieved due to an error."

def hybrid_rag_system(user_query: str) -> str:
    """
    Integrates real-time search with the base language model to generate a grounded response.
    """
    search_results = get_realtime_search_results(user_query)
    
    if "Real-time search results could not be retrieved" in search_results or "No search results found" in search_results:
        prompt_with_search_results = f"""
        I was unable to retrieve external real-time search results for the user's query. Please answer the user's query based solely on your internal knowledge or acknowledge that external information is unavailable.

        User Query: {user_query}
        """
    else:
        prompt_with_search_results = f"""
        Based on the following search results and your own knowledge, please answer the user's query.

        Search Results:
        {search_results}

        User Query: {user_query}
        """

    try:
        completion = client.chat.completions.create(
            model="nvidia/llama-3.3-nemotron-super-49b-v1.5",
            messages=[
                {"role": "system", "content": "You are a helpful AI assistant that provides grounded answers based on provided information."},
                {"role": "user", "content": prompt_with_search_results}
            ],
            temperature=0.6,
            top_p=0.95,
            max_tokens=1024,
            frequency_penalty=0,
            presence_penalty=0,
            stream=False
        )

        if completion.choices and completion.choices[0].message and completion.choices[0].message.content:
            model_response = completion.choices[0].message.content.strip()
            return model_response
        else:
            return "No response generated by the model."
    except Exception as e:
        print(f"Error calling base model: {e}")
        return f"Error: {e}"

def chat_interface(message, history):
    """
    Function mapping Gradio chat message to the RAG system
    """
    return hybrid_rag_system(message)

# Build the Gradio interface
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🚀 Nvidia LLaMA Hybrid RAG Chatbot")
    gr.Markdown("A hybrid RAG system using `nvidia/llama-3.3-nemotron-super-49b-v1.5` and `SerpAPI` for real time search grounding.")
    
    chatbot = gr.ChatInterface(
        fn=chat_interface,
        examples=[
            "What are the latest developments in AI technology?",
            "Who won the last Super Bowl?",
            "What is the current weather in London?"
        ],
        title="Hybrid RAG Assistant"
    )

if __name__ == "__main__":
    demo.launch(server_port=7860, share=False)
